---
#
# Ansible managed
#
repository:
  description: Setup exports on an nfs server
  homepage: https://robertdebock.nl/
  topics: nfs, nfsserver, exports, system, networking, ansible, molecule, tox, playbook
