---
# handlers file for nfsserver

- name: Reload exports
  ansible.builtin.command:
    cmd: exportfs -ra
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
