---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-nfsserver
      nfsserver_exports:
        - share: /mnt/export
          owner: root
          group: root
          mode: "0755"
          hosts:
            - name: "10.0.0.0/24"
              options:
                - ro
                - no_subtree_check
                - nohide
            - name: "172.16.0.0/24"
              options:
                - rw
                - sync
                - no_wdelay
        - share: /mnt/export2
          owner: root
          group: root
          mode: "0755"
          hosts:
            - name: "10.2.3.0/24"
              options:
                - ro
