---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check exports
      ansible.builtin.command:
        cmd: showmount --exports
      register: nfsserver_check_exports
      failed_when:
        - "'/mnt/export' not in nfsserver_check_exports.stdout"
        - "'/mnt/export2' not in nfsserver_check_exports.stdout"
      when:
        - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
